


# 1. Custom Reset Logic Configuration
password-reset:
  expiry-minutes: 30

# 2. Server Settings
server:
  port: 8081

# 3. Main Spring Configuration
spring:
  application:
    name: auth-service
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true

  # Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3307/auth_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: pmg82004
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  mail:
    host: smtp.sendgrid.net
    port: 587
    username: apikey
    password: ${SENDGRID_API_KEY}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# 4. App URLs
app:
  mail:
    from: unevallalit6499@gmail.com
  frontend:
    url: http://localhost:4200/reset-password?token=
  backend:
    url: http://localhost:8081

# 5. Service Discovery (Eureka)
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.57:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost


