

spring.application.name=auth-service
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

# Fix hostname for cloud deployment
eureka.instance.hostname=projectbackend-authservice.onrender.com
eureka.instance.prefer-ip-address=false
eureka.instance.non-secure-port=443
eureka.instance.non-secure-port-enabled=true
eureka.instance.secure-port-enabled=false
eureka.client.service-url.defaultZone=https://projectbackend-serviceregistery-1.onrender.com/eureka/


#spring.boot.admin.client.url=http://192.168.1.23:1111
#
## Ensure Actuator endpoints are exposed and enabled
##this will help to explore all the endpoint of our app. like logs, metrics , helath or our app etc..
##spring do not share all the endpoint due to security reason so by enabling this one we can get internal endpoint
#management.endpoints.web.exposure.include=*
##management.endpoint.health.show-details=always
#
## Enable the registration task explicitly
#spring.boot.admin.client.registration.enabled=true
#
#logging.file.name=logs/auth-service